//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string numeroTelefono { get; set; }
        public string direccion { get; set; }
        public string cedula { get; set; }
        public string noTarjetaCr { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public string TipoPersona { get; set; }
    }
}
