//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public int IdDevolucion { get; set; }
        public int IdRenta { get; set; }
        public string detallesDevolucion { get; set; }
        public System.DateTime fechaDevolucion { get; set; }
    }
}
