//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Decision { get; set; }
        public string numeroTelefono { get; set; }
        public string cedula { get; set; }
        public string tandaLaboral { get; set; }
        public Nullable<int> porcientocomision { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
    
        public virtual procesoInspeccion procesoInspeccion { get; set; }
    }
}
