//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int IdModelo { get; set; }
        public int IdMarca { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Marca Marca { get; set; }
    }
}
