//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesoInspeccion
    {
        public int IdInspeccion { get; set; }
        public int IdVehiculo { get; set; }
        public string detalleInspeccion { get; set; }
        public Nullable<bool> tieneRalladura { get; set; }
        public string CantidadCombustible { get; set; }
        public Nullable<bool> TieneGomarepuesta { get; set; }
        public Nullable<bool> TieneGato { get; set; }
        public Nullable<bool> TieneRoturasCristal { get; set; }
        public string estadoGoma { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idempleado { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
