//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta
    {
        public int IdRenta { get; set; }
        public int IdVehiculo { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaRenta { get; set; }
        public string DetalleRenta { get; set; }
        public string FechaDevolucion { get; set; }
        public Nullable<decimal> montopordia { get; set; }
        public Nullable<int> CantidadDias { get; set; }
    
        public virtual vehiculo vehiculo { get; set; }
    }
}
