//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentCarEntities2 : DbContext
    {
        public rentCarEntities2()
            : base("name=rentCarEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Modelo> Modeloes { get; set; }
        public virtual DbSet<procesoInspeccion> procesoInspeccions { get; set; }
        public virtual DbSet<Renta> Rentas { get; set; }
        public virtual DbSet<tiposDeCombustible> tiposDeCombustibles { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculoes { get; set; }
        public virtual DbSet<vehiculo> vehiculos { get; set; }
        public virtual DbSet<Devolucion> Devolucions { get; set; }
        public virtual DbSet<Reportevehiculo> Reportevehiculos { get; set; }
        public virtual DbSet<Reporte> Reportes { get; set; }
        public virtual DbSet<VehiculosRentado> VehiculosRentados { get; set; }
    }
}
