//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public System.DateTime FechaRenta { get; set; }
        public string DetalleRenta { get; set; }
        public string NombreVehiculo { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Combustible { get; set; }
        public string Cliente { get; set; }
    }
}
