//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposDeCombustible
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tiposDeCombustible()
        {
            this.vehiculos = new HashSet<vehiculo>();
        }
    
        public int IdCombustible { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual tiposDeCombustible tiposDeCombustible1 { get; set; }
        public virtual tiposDeCombustible tiposDeCombustible2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiculo> vehiculos { get; set; }
    }
}
