//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculo()
        {
            this.Rentas = new HashSet<Renta>();
        }
    
        public int IdVehiculos { get; set; }
        public string Nombre { get; set; }
        public int IdMarca { get; set; }
        public int IdTipoVehiculo { get; set; }
        public int IdCombustible { get; set; }
        public string nochasis { get; set; }
        public string nomotor { get; set; }
        public string noplaca { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual tiposDeCombustible tiposDeCombustible { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta> Rentas { get; set; }
    }
}
