//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarGonzalez
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosRentado
    {
        public int IdRenta { get; set; }
        public string nombreVehiculo { get; set; }
        public Nullable<bool> estado { get; set; }
        public int IdVehiculos { get; set; }
    }
}
